openapi: 3.0.1
servers: []
info:
  version: "1.0.0"
  title: Swagger Cassandra API
tags:
  - name: cassandra
paths:
  /api/cassandra:
    post:
      tags:
        - cassandra
      summary: Add a new entry in cassandra
      operationId: addCassandra
      responses:
        '405':
          description: Invalid input
    put:
      tags:
        - cassandra
      summary: Update an existing entry
      operationId: updateCassandra
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Entry not found
        '405':
          description: Validation exception
    get:
      tags:
        - cassandra
      summary: List all entries
      description: Returns all entries
      operationId: getAllCassandra
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  '/api/cassandra/{id}':
    get:
      tags:
        - cassandra
      summary: Find entry by ID
      description: Returns a single entry
      operationId: getCassandra
      parameters:
        - name: id
          in: path
          description: ID of entry to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid ID supplied
        '404':
          description: Entry not found
    delete:
      tags:
        - cassandra
      summary: Deletes an entry in cassandra
      operationId: deleteCassandra
      parameters:
        - name: id
          in: path
          description: Entry id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Entry not found
